### ISSUE TITLE
Transcribing

### ISSUE THREAD

**Issue by ghost** [xk-wang/transition-aware#2]
Hello, I'm only a musician who is very interested in your project looking forward to trying it out. I set it up in Colab and am currently stuck with an error at the onsets stage. I also wanted to contribute the colab in case it is useful: 

https://colab.research.google.com/drive/1q0lk7oDEummGQKVLtx2lt6Cdmhr789GN?usp=sharing

_(Also, it didn't let me install cudatoolkits and cudnn, but i could get the first one by using another command)_

```/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/dist-packages/librosa/core/audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
<multiprocessing.pool.MapResult object at 0x7fe617346588>
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmphi9h_48h
13 Track13.tfrecords
Traceback (most recent call last):
  File "code/predict_onset.py", line 144, in <module>
    main(args)
  File "code/predict_onset.py", line 122, in main
    for idx, prediction in enumerate(predictions):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py", line 543, in predict
    features, None, model_fn_lib.ModeKeys.PREDICT, self.config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "code/predict_onset.py", line 90, in model_fn
    tf.train.init_from_checkpoint(params['ckpt_path'], onset_scope)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 183, in init_from_checkpoint
    reader = load_checkpoint(ckpt_dir_or_file)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 63, in load_checkpoint
    return pywrap_tensorflow.NewCheckpointReader(filename)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 306, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: not an sstable (bad magic number)
```

Thanks

**Comment by xk-wang** [comment]
from your colab. cudatoolkit installation failed. You should use conda install cudatoolkit  instead of pip.
`Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting tensorflow-gpu==1.13.1
  Using cached tensorflow_gpu-1.13.1-cp36-cp36m-manylinux1_x86_64.whl (345.2 MB)
ERROR: Could not find a version that satisfies the requirement cudatookit==10.0.130 (from versions: none)
ERROR: No matching distribution found for cudatookit==10.0.130`

**Comment by ghost** [comment]
Thanks for your help. I'm encountering a new error: `AttributeError: module 'tensorflow' has no attribute 'contrib'`, It'd be great if you had any idea how to fix that. Thanks
